### PR TITLE
Update to 2.4.2 release

### PR DESCRIPTION
**Pull request by mbyczkowski**
Ruby 2.4.2 has just been [released](https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/) today. I've read thru a bunch of docs and READMEs, but I'm still not sure if this is the right way to bump Ruby version for official Docker images. Lemme know if I need to do anything else. 🙂

### CODE REVIEW

**Comment by tianon** [comment]
Unfortunately, if we merge this, @docker-library-bot will revert it shortly afterwards since it runs `./update.sh` on a periodic task, and `./update.sh` is not picking up this release for some reason.

Digging in, it _appears_ to be because while this release has been announced in the "News", it isn't listed on https://www.ruby-lang.org/en/downloads/releases/ yet. :disappointed: :confused:

**Comment by mbyczkowski** [comment]
@tianon that makes sense! I saw the @docker-library-bot in the commits, but had no idea that it'll automatically pick up ruby and rubygems releases. A short line in readme about auto-updating would be 💯

**Comment by patientdev** [comment]
What's the process for getting this into the the `official-images` repo?

**Comment by yosifkit** [comment]
The automated `update.sh` job is currently running (see the bottom of the [readme](https://github.com/docker-library/ruby/commit/083a412b5d9da36614b02e36bae39518f7948f04)).  Once that finishes we can make the PR to official images.

Duplicate issues: #152 #153 #154 #156 #157.

**Pull request closed without merging**
