### PR TITLE
Add explicit "jessie" and "alpine3.4" aliases

### PR DESCRIPTION
**Pull request by tianon**
See also https://github.com/docker-library/golang/pull/170, https://github.com/docker-library/python/pull/215.

Ref #141

### CODE REVIEW

**Comment by tianon** [comment]
```console
$ ./generate-stackbrew-library.sh
# this file is generated via https://github.com/docker-library/ruby/blob/a6918175fd506b46bf2d8f899f4faa40e72296fb/generate-stackbrew-library.sh

Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
             Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/ruby.git

Tags: 2.4.1-jessie, 2.4-jessie, 2-jessie, jessie, 2.4.1, 2.4, 2, latest
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.4/jessie

Tags: 2.4.1-slim, 2.4-slim, 2-slim, slim
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.4/jessie/slim

Tags: 2.4.1-onbuild, 2.4-onbuild, 2-onbuild, onbuild
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.4/jessie/onbuild

Tags: 2.4.1-alpine3.4, 2.4-alpine3.4, 2-alpine3.4, alpine3.4, 2.4.1-alpine, 2.4-alpine, 2-alpine, alpine
Architectures: amd64
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.4/alpine3.4

Tags: 2.3.4-jessie, 2.3-jessie, 2.3.4, 2.3
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.3/jessie

Tags: 2.3.4-slim, 2.3-slim
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.3/jessie/slim

Tags: 2.3.4-onbuild, 2.3-onbuild
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.3/jessie/onbuild

Tags: 2.3.4-alpine3.4, 2.3-alpine3.4, 2.3.4-alpine, 2.3-alpine
Architectures: amd64
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.3/alpine3.4

Tags: 2.2.7-jessie, 2.2-jessie, 2.2.7, 2.2
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.2/jessie

Tags: 2.2.7-slim, 2.2-slim
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.2/jessie/slim

Tags: 2.2.7-onbuild, 2.2-onbuild
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.2/jessie/onbuild

Tags: 2.2.7-alpine3.4, 2.2-alpine3.4, 2.2.7-alpine, 2.2-alpine
Architectures: amd64
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.2/alpine3.4
```

**Comment by tianon** [comment]
```diff
$ diff -u <(bashbrew list ruby | cut -d: -f2 | sort -V) <(bashbrew list <(./generate-stackbrew-library.sh) | cut -d: -f2 | sort -V)
--- /dev/fd/63	2017-07-31 16:49:32.397953866 -0700
+++ /dev/fd/62	2017-07-31 16:49:32.398953837 -0700
@@ -1,32 +1,48 @@
 2
 2-alpine
+2-alpine3.4
+2-jessie
 2-onbuild
 2-slim
 2.2
 2.2-alpine
+2.2-alpine3.4
+2.2-jessie
 2.2-onbuild
 2.2-slim
 2.2.7
 2.2.7-alpine
+2.2.7-alpine3.4
+2.2.7-jessie
 2.2.7-onbuild
 2.2.7-slim
 2.3
 2.3-alpine
+2.3-alpine3.4
+2.3-jessie
 2.3-onbuild
 2.3-slim
 2.3.4
 2.3.4-alpine
+2.3.4-alpine3.4
+2.3.4-jessie
 2.3.4-onbuild
 2.3.4-slim
 2.4
 2.4-alpine
+2.4-alpine3.4
+2.4-jessie
 2.4-onbuild
 2.4-slim
 2.4.1
 2.4.1-alpine
+2.4.1-alpine3.4
+2.4.1-jessie
 2.4.1-onbuild
 2.4.1-slim
 alpine
+alpine3.4
+jessie
 latest
 onbuild
 slim
```

**Comment by tianon** [comment]
(This change is pretty much identical to https://github.com/docker-library/python/pull/215, minus the Windows bits.)

**Comment by yosifkit** [comment]
What is the verdict on `stretch-slim` and `jessie-slim`?  I didn't see a written discussion in https://github.com/docker-library/python/pull/215 and figured it will also come up on images later.  What is the case for rejecting distro specific slim images?

I know we informally rejected the `jessie-onbuild` in `golang` since onbuild was being phased out.

**Comment by tianon** [comment]
I think we discussed that briefly and determined that it ought to be `slim-jessie`, if we decide that's something we're OK with doing (to make it clear this is a "jessie" sub-variant of the "slim" variant), not necessarily something based on `debian:jessie-slim` (although in many cases might be).

**Comment by yosifkit** [comment]
That sounds right.  Do we want to add them now, so that users will start specifying Debian release in their slim images too?

**Comment by tianon** [comment]
```console
$ ./generate-stackbrew-library.sh
# this file is generated via https://github.com/docker-library/ruby/blob/05a198ca89a5cb563a857d0d6f060abcbd6eb8e4/generate-stackbrew-library.sh

Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
             Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/ruby.git

Tags: 2.4.1-jessie, 2.4-jessie, 2-jessie, jessie, 2.4.1, 2.4, 2, latest
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.4/jessie

Tags: 2.4.1-slim-jessie, 2.4-slim-jessie, 2-slim-jessie, slim-jessie, 2.4.1-slim, 2.4-slim, 2-slim, slim
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.4/jessie/slim

Tags: 2.4.1-onbuild, 2.4-onbuild, 2-onbuild, onbuild
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.4/jessie/onbuild

Tags: 2.4.1-alpine3.4, 2.4-alpine3.4, 2-alpine3.4, alpine3.4, 2.4.1-alpine, 2.4-alpine, 2-alpine, alpine
Architectures: amd64
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.4/alpine3.4

Tags: 2.3.4-jessie, 2.3-jessie, 2.3.4, 2.3
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.3/jessie

Tags: 2.3.4-slim-jessie, 2.3-slim-jessie, 2.3.4-slim, 2.3-slim
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.3/jessie/slim

Tags: 2.3.4-onbuild, 2.3-onbuild
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.3/jessie/onbuild

Tags: 2.3.4-alpine3.4, 2.3-alpine3.4, 2.3.4-alpine, 2.3-alpine
Architectures: amd64
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.3/alpine3.4

Tags: 2.2.7-jessie, 2.2-jessie, 2.2.7, 2.2
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.2/jessie

Tags: 2.2.7-slim-jessie, 2.2-slim-jessie, 2.2.7-slim, 2.2-slim
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.2/jessie/slim

Tags: 2.2.7-onbuild, 2.2-onbuild
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.2/jessie/onbuild

Tags: 2.2.7-alpine3.4, 2.2-alpine3.4, 2.2.7-alpine, 2.2-alpine
Architectures: amd64
GitCommit: a6918175fd506b46bf2d8f899f4faa40e72296fb
Directory: 2.2/alpine3.4
```

**Comment by tianon** [comment]
```diff
$ diff -u <(bashbrew list ruby | cut -d: -f2 | sort -V) <(bashbrew list <(./generate-stackbrew-library.sh) | cut -d: -f2 | sort -V)
--- /dev/fd/63	2017-08-03 14:09:00.478657126 -0700
+++ /dev/fd/62	2017-08-03 14:09:00.479657097 -0700
@@ -1,32 +1,56 @@
 2
 2-alpine
+2-alpine3.4
+2-jessie
 2-onbuild
 2-slim
+2-slim-jessie
 2.2
 2.2-alpine
+2.2-alpine3.4
+2.2-jessie
 2.2-onbuild
 2.2-slim
+2.2-slim-jessie
 2.2.7
 2.2.7-alpine
+2.2.7-alpine3.4
+2.2.7-jessie
 2.2.7-onbuild
 2.2.7-slim
+2.2.7-slim-jessie
 2.3
 2.3-alpine
+2.3-alpine3.4
+2.3-jessie
 2.3-onbuild
 2.3-slim
+2.3-slim-jessie
 2.3.4
 2.3.4-alpine
+2.3.4-alpine3.4
+2.3.4-jessie
 2.3.4-onbuild
 2.3.4-slim
+2.3.4-slim-jessie
 2.4
 2.4-alpine
+2.4-alpine3.4
+2.4-jessie
 2.4-onbuild
 2.4-slim
+2.4-slim-jessie
 2.4.1
 2.4.1-alpine
+2.4.1-alpine3.4
+2.4.1-jessie
 2.4.1-onbuild
 2.4.1-slim
+2.4.1-slim-jessie
 alpine
+alpine3.4
+jessie
 latest
 onbuild
 slim
+slim-jessie
```

**Pull request merged**
