### PR TITLE
Ruby 3.0.0 is released

### PR DESCRIPTION
**Pull request by mtsmfm**
https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

I've generated these files via the following command:

```
$ mv 3.0-rc 3.0
$ docker run --rm -v $PWD:/app -w /app ruby ./update.sh
```

### CODE REVIEW

**Comment by tianon** [comment]
LGTM, thanks!

However the downstream PR likely won't happen (and certainly won't merge) until after the holiday. 🎄

**Comment by mtsmfm** [comment]
> However the downstream PR likely won't happen (and certainly won't merge) until after the holiday. 🎄

Noted.
Thank you for letting me know! 🎄

**Comment by tianon** [comment]
We also need to update `generate-stackbrew-library.sh` (didn't notice until post-merge; sorry!)

I'll get it later if nobody else beats me to it.

**Comment by mtsmfm** [comment]
@tianon Sorry, I've fixed alias setting for `generate-stackbrew-library.sh`.

https://github.com/docker-library/ruby/pull/333

**Pull request merged**
