### PR TITLE
Update 2.7 to preview2 version

### PR DESCRIPTION
**Pull request by sdwolfz**
Released on 22 Oct 2019: https://www.ruby-lang.org/en/news/2019/10/22/ruby-2-7-0-preview2-released/

This is an initial attempt and might not work (or need some cleanup).

### CODE REVIEW

**Comment by sdwolfz** [comment]
Any suggestions about the missing requires? I'm afraid I don't know how to proceed.

```
require 'cmath' failed: cannot load such file -- cmath
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
./container.rb:121:in `block in <main>'
./container.rb:118:in `each'
./container.rb:118:in `<main>'

require 'scanf' failed: cannot load such file -- scanf
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
./container.rb:121:in `block in <main>'
./container.rb:118:in `each'
./container.rb:118:in `<main>'

require 'shell' failed: cannot load such file -- shell
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
./container.rb:121:in `block in <main>'
./container.rb:118:in `each'
./container.rb:118:in `<main>'

require 'sync' failed: cannot load such file -- sync
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
./container.rb:121:in `block in <main>'
./container.rb:118:in `each'
./container.rb:118:in `<main>'

require 'thwait' failed: cannot load such file -- thwait
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
./container.rb:121:in `block in <main>'
./container.rb:118:in `each'
./container.rb:118:in `<main>'
```

**Comment by yosifkit** [comment]
The bump would've been automatic, but ruby has removed "unmaintained libraries" from 2.7: https://bugs.ruby-lang.org/issues/16170 (which is why the build test is failing). I'll go fix the tests to skip those libs for 2.7+.

**Comment by sdwolfz** [comment]
@yosifkit OK, that makes sense, thanks.

**Comment by tianon** [comment]
After the tests were fixed, the bot hit this automatically in 1dd5c255325fa0d5c3761f5238bbe1a9f50e9596, but merging this as well is harmless. :+1: :heart:

**Pull request merged**
