### PR TITLE
Slim for all the versions

### LINKED ISSUE #30: ruby:slim!

### PR DESCRIPTION
**Pull request by yosifkit**
Sizes and tests coming monday.

Fixes #30

### CODE REVIEW

**Comment by tianon** [comment]
Ahh, nice.  You've got the end-result sizes handy?

**Comment by yosifkit** [comment]
```
REPOSITORY          TAG                  IMAGE ID            CREATED             VIRTUAL SIZE
ruby                2.2.0-slim           0df822a25dfb        2 days ago          294.7 MB
ruby                2.1.5-slim           a4913abd2ab4        2 days ago          296.8 MB
ruby                2.0.0-p598-slim      6ad4dd8f057c        2 days ago          285.3 MB
ruby                1.9.3-p551-slim      529525dbf1ef        2 days ago          254.3 MB

ruby                2.2.0-wheezy         54227d0d46eb        2 days ago          635.2 MB
ruby                2.1.5-wheezy         069fa048d11d        2 days ago          636.7 MB
ruby                2.0.0-p598-wheezy    23a67656d025        2 days ago          625.5 MB
ruby                1.9.3-p551-wheezy    4a3e0d0f46f4        2 days ago          591.9 MB

ruby                2.2.0                b8b541ff03c0        2 days ago          774.5 MB
ruby                2.1.5                1a61ec70ce96        2 days ago          776.6 MB
ruby                2.0.0-p598           a4390de3ffbb        2 days ago          765.4 MB
ruby                1.9.3-p551           ce298cabb9db        2 days ago          730.4 MB

ruby                2.2.0-onbuild        0fbca023bd5c        2 days ago          774.5 MB
ruby                2.1.5-onbuild        480ecda9b5bd        2 days ago          776.6 MB
ruby                2.0.0-p598-onbuild   8d2a41ed5fed        2 days ago          765.4 MB
ruby                1.9.3-p551-onbuild   5d02e2be3e9e        2 days ago          730.4 MB
```

**Comment by tianon** [comment]
That's hawt. :heart_eyes:

Feel free to merge if the tests we've written so far pass. :heart:

**Comment by yosifkit** [comment]
Merging:
```console
testing ruby:1.9.3-p551-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:1.9.3-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:1.9-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:1-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:2.0.0-p598-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:2.0.0-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:2.0-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:2.1.5-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:2.1-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:2.2.0-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:2.2-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:2-slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
testing ruby:slim
	'utc' [1/4]...passed
	'ruby-standard-libs' [2/4]...passed
	'ruby-gems' [3/4]...skipping
	'ruby-bundler' [4/4]...skipping
```

**Pull request merged**
