### PR TITLE
update rubygems to 2.4.8

### LINKED ISSUE #47: Run `gem update --system $RUBYGEMS_VERSION`
I propose that rubygems be treated much like bundler, explicitly installing the latest version.  Lines like these would be added to each build:

```Dockerfile
ENV RUBYGEMS_VERSION 2.4.8
RUN gem update --system $RUBYGEMS_VERSION
```

2.4.8 is the current version of rubygems as of this post.  The lowest supported ruby version is 2.0.0, which ships with rubygems 2.0.14.  Backwards compatibility is a central goal of the rubygems maintainers, so new versions works with ruby versions at least as far back as 1.9.x.  The changes between 2.0.14 and 2.4.8 add features and fix many security vulnerabilities.

I will gladly do the typing for this, but are there any objections?

### PR DESCRIPTION
**Pull request by nicknovitski**
Closes #47, but I need to rebase it into a single commit before it can be merged.

To reiterate the issue, the idea is to explicitly manage rubygems versions, just as is done with bundler.

### CODE REVIEW

**Comment by tianon** [comment]
Doesn't this need to happen in the same `RUN` line as installing Ruby to avoid unnecessary layer bloat due to having `rubygems` installed with `ruby` and then immediately replaced in a following line with a newer version?

(ala, the same way we handle `pip` in newer `python`: https://github.com/docker-library/python/blob/3e5826ad0c6e29f07f6dc7ff8f30b4c54385d1bb/3.4/Dockerfile#L30)

**Comment by nicknovitski** [comment]
Good point, I'm on it.

**Comment by nicknovitski** [comment]
[Looks like](https://travis-ci.org/docker-library/ruby/jobs/74162225#L1782-L1783) I should move the command up a few lines?  I'll try it later today.

**Comment by nicknovitski** [comment]
Yeah, the problem was the line in the "and-chain" that deletes the working directory.  `gem install` can't handle that.  Updating before deleting seems to work.

I also added `--no-document` to the update, to keep this from happening:
```
Installing ri documentation for rubygems-update-2.4.8
Installing darkfish documentation for rubygems-update-2.4.8
```

Before any `update --system`, the lowest version of rubygems in a supported image is 2.0.14, which already supports the `--no-document` flag.  I noticed that the containers configure the default flags of `--no-rdoc` and `--no-ri`.  Sadly, that does not exclude "darkfish," a documentation format some gems use nowadays, as you can see.

Is it alright if I add a commit updating those default flags?

**Comment by tianon** [comment]
LGTM :+1:

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
Also, +1 for swapping our `--no-rdoc` and `--no-ri` for `--no-document` -- @nicknovitski do you want dibs on that PR? :smile:

**Comment by nicknovitski** [comment]
Haha, sure.

**Pull request merged**
