### PR TITLE
Build Ruby-slim with jemalloc

### PR DESCRIPTION
**Pull request by jvrplmlmn**
Using `jemalloc` can decrease memory usage considerably:

https://www.levups.com/en/blog/2017/optimize_ruby_memory_usage_jemalloc_heroku_scalingo.html
https://medium.com/@adrienjarthon/ruby-jemalloc-results-for-updown-io-d3fb2d32f67f

This PR updates the Ruby slim template to be built with `jemalloc`.

### CODE REVIEW

**Comment by tianon** [comment]
Do we have an official recommendation from Ruby upstream we can point to
for building in this way?

**Comment by shaneog** [comment]
@tianon There is a discussion in the bugtracker which it is acknowledged that _jemalloc_ is better, but that it can't be set as the default due to vagaries of different platforms.
https://bugs.ruby-lang.org/issues/9113

Since this image is based on Debian I can't see any reason for not doing this - it really is a huge benefit.

**Comment by codenamev** [comment]
It looks like this has been [resolved upstream](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/46354) so that ruby can now be configured to use `--with-jemalloc`.  [As noted by @nobu](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/46354https://bugs.ruby-lang.org/issues/9113#note-39), you have to configure jemalloc `--with-jemalloc-prefix` as well.

**Comment by jorihardman** [comment]
If anyone is looking to run this now, I've forked this repository, merged this PR, and added a public/automated docker hub that can be found here: https://hub.docker.com/r/swipesense/ruby-jemalloc

We've been using this in production for a couple weeks now and have seen great results. I will maintain that docker hub and repo until this or a similar PR is merged.

**Comment by yosifkit** [comment]
Closing PR until a recommendation from Ruby upstream. Discussion can continue on #182.

See also https://github.com/docker-library/ruby/issues/182#issuecomment-456221587

**Pull request closed without merging**
