### PR TITLE
Upgrade 2.6

### PR DESCRIPTION
**Pull request by booink**
Ruby 2.6.0 is released.

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@yosifkit :+1:

**Comment by n-rodriguez** [comment]
cnhq5udveaaoo8g jpg large

**Comment by bquorning** [comment]
I think you need to 1) remove 2.6-rc, and 2) change generate-stackbrew-library.sh – see #178 from when 2.5 was released.

**Comment by n-rodriguez** [comment]
I love the new Github censorship feature ("This comment was marked as off-topic") :)

**Pull request merged**
