### PR TITLE
Remove BUNDLE_BIN and add GEM_HOME/bin back to PATH

### PR DESCRIPTION
**Pull request by tianon**
See https://github.com/docker-library/ruby/pull/208#issuecomment-390755292

This is a follow-up to #208.

Refs #188, #191, #193

### CODE REVIEW

**Comment by tianon** [comment]
I tested with both `Dockerfile`s from #208's description, and they both still build successfully (and `rake` is in `PATH` after the build, and I'm able to `gem install passenger` and get `passenger-config` in `PATH`, which is how we noticed this breakage in the first place).

**Comment by tianon** [comment]
I wonder if this means we should at least partially revert https://github.com/docker-library/docs/pull/1221 too?  I guess it's still pretty relevant.

**Comment by tianon** [comment]
Yay green finally!

**Comment by mvisonneau** [comment]
Thanks for the fix @tianon. Any idea when this is going to be merged and released ? I believe that a lot of people are going to be impacted by the recent release on most tags that breaks the gems binary path.

**Comment by tianon** [comment]
Doh, good point; @yosifkit can you review this ASAP today? 😇

**Comment by mvisonneau** [comment]
thanks 🙏 !

**Comment by Mehonoshin** [comment]
It looks like dockerhub still contains broken images.

I get the following with the latest image from there

```
 /bin/sh: 1: rails: not found
The command '/bin/sh -c rails assets:precompile' returned a non-zero code: 127
```

**Comment by Mehonoshin** [comment]
It looks like it does not work when I use `bundle install --deployment --without development test`
With regular, full installation it works.
@tianon do you have any ideas, why could that happen?

**Comment by tianon** [comment]
Gah, `bundle install --deployment` drops bits into `./vendor/bundle/...` instead of the normal Bundler directory. :disappointed:

From https://bundler.io/v1.0/man/bundle-install.1.html#DEPLOYMENT-MODE:

> Gems are installed to `vendor/bundle` not your default system location

Was `BUNDLE_BIN` putting even those binstubs in `/usr/local/bundler/bin` before?

**Comment by Mehonoshin** [comment]
yep, it worked before

**Comment by bkeroackdsc** [comment]
Any chance we can get this applied to the ruby 2.1.x image as well?

**Comment by tianon** [comment]
Unfortunately not, Ruby 2.1 is unsupported (both by us and by Ruby
upstream), but it shouldn't be too much work to find the old Dockerfile we
used and update it with this change yourself for your own builds (which is
a good idea regardless if you rely on that old version).

**Comment by bkeroackdsc** [comment]
Fair enough. Thanks for the response!

**Pull request merged**
