### PR TITLE
Add Alpine to all versions

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by yosifkit** [comment]
:cry: https://travis-ci.org/docker-library/ruby/jobs/105739823#L947

**Comment by tianon** [comment]
Ouch: https://bugs.ruby-lang.org/issues/8051

**Comment by tianon** [comment]
https://github.com/ruby/ruby/commit/b945ad289f14c1b1ba65bdd9a4e1106f3cee134c -- only applied from v2.1 onwards

**Comment by tianon** [comment]
I'm thinking that it's probably worth just dropping 2.0's Alpine variant instead of trying to maintain that backported patch ourselves.

**Comment by tianon** [comment]
According to https://www.ruby-lang.org/en/news/2015/12/16/ruby-2-0-0-p648-released/, Ruby 2.0 will be EOL on Feb. 24th, 2016 anyhow.

**Comment by tianon** [comment]
Updated to remove `2.0/alpine`.

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
