### PR TITLE
Upgrade to Ruby 3.3.1

### PR DESCRIPTION
**Pull request by henrikbjorn**
3.3.1 was released https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-3-1-released/

### CODE REVIEW

**Comment by frederikspang** [comment]
We should probably Update all new version. Several versions have been patched in addition to 3.3.x

**Comment by henrikbjorn** [comment]
> We should probably Update all new version. Several versions have been patched in addition to 3.3.x

After creating the PR I saw an `update.sh` script and with some of the other updates it seems there is a bot doing the heavy lifting.

**Comment by Earlopain** [comment]
Yeah, these patch releases are done automatically. Update checks are done every 6 hours, should happen in 3 now. You can follow along at https://doi-janky.infosiftr.net/job/update.sh/job/ruby

**Comment by tianon** [comment]
For this to work, it also needs to update `versions.json`, as `versions.sh`/`apply-templates.sh` would do (or `update.sh` if you want something that runs both at once).

Also, we've got 3.2.4, 3.1.5, _and_ 3.0.7 that also have security updates and need similar treatment.  I've opened a PR at https://github.com/docker-library/ruby/pull/446 which includes all the necessary changes and all versions. :+1:

**Comment by henrikbjorn** [comment]
@tianon Is it possible to get a `CONTRIBUTING.md` document or document how to update the different versions in the readme?

Seems there is a automated way of doing it.

**Pull request closed without merging**
