### PR TITLE
[WIP] Compile jessie-slim with jemalloc

### PR DESCRIPTION
**Pull request by libo**
related to https://github.com/docker-library/ruby/issues/182

### CODE REVIEW

**Comment by jonmoter** [comment]
I think what we'll want to do is modify the `*.template` files, and have the `Dockerfiles` be generated.

**Comment by laiskajoonas** [comment]
What are the odds of this getting merged?

**Comment by yosifkit** [comment]
@laiskajoonas,

> I think we were still uncertain whether this is the recommended or endorsed way to build ruby according to ruby upstream. We try to keep the images as close to upstream release recommendations as possible.
>
> \- https://github.com/docker-library/ruby/pull/198#issuecomment-402278276

**Comment by yosifkit** [comment]
Closing PR until a recommendation from Ruby upstream. Discussion can continue on #182.

See also https://github.com/docker-library/ruby/issues/182#issuecomment-456221587

**Pull request closed without merging**
