### PR TITLE
Added Stretch to 2.7 Stable

### PR DESCRIPTION
**Pull request by Shleeble**

### CODE REVIEW

**Comment by Shleeble** [comment]
@tianon please consider this for merging.

**Comment by tianon** [comment]
Not sure I understand the use case; can you please elaborate on why you
want this?

**Comment by Shleeble** [comment]
This is just for backwards compatibility.

My usecase is Mastodon. This is a Ruby heavy application and some of the gems don't work out of the box... so going from 2.6-stretch to 2.7-buster won't work on our circleci tests.

* libicudata.57 is not available in buster (63). https://packages.debian.org/buster/libicu-dev
* Protobuf.10 is not avaiable in buster (17). https://packages.debian.org/buster/libprotobuf-dev

**Comment by yosifkit** [comment]
With Debian Stretch moving to end of life in 2020 (https://wiki.debian.org/DebianReleases), I am very hesitant to add it to the new version of ruby since it will possibly go away in 6 months.

**Comment by tianon** [comment]
Still not sure I understand what the issue with Mastodon is.  I did some testing against https://github.com/tootsuite/mastodon, and had the following experience:

1. https://github.com/tootsuite/mastodon/blob/3b3bdc7293493735a2169d3377a5a5b7d9006497/Gemfile#L4 is obviously the first hurdle

2. after adjusting that, I ran into the issue with `cld3` having the same (which you filed at https://github.com/tootsuite/mastodon/issues/12704 / https://github.com/akihikodaki/cld3-ruby/issues/21 / https://github.com/akihikodaki/cld3-ruby/pull/22)

3. once I installed `libprotobuf-dev` and `protobuf-compiler`, I was able to successfully `gem install cld3 -v '3.2.4' --source 'https://rubygems.org/' --force`, so I think that'll be relatively easy to overcome

4. I then ran into `microformats` having the exact same, which after installing `libidn11-dev` also was able to `gem install --force` successfully

At this point, I commented out `cld3` and `microformats` from the Mastodon `Gemfile` (because I couldn't figure out how to convince `bundler` to also pass `--force` for those particular gems) and it was able to complete successfully.

**Comment by Shleeble** [comment]
I was unaware of the Stretch EOL of 2020. As my issue is exclusively with the Gems I'm using on Buster... which I've resolved - Mastodon is currently testing on Buster. 

I'll close this request - unless others raise their own concerns

**Pull request closed without merging**
