### PR TITLE
Append ruby 2.5 on Alpine 3.6

### LINKED ISSUE #233: build 2.5.1 with Alpine 3.6 due to sidekick Segfaults
Hello,

Mastodon is built with sidekick and we're recently committed from `ruby2.4.4-alpine3.6` to `ruby2.5.1-alpine3.7`... but have had to revert due to segfaults with sidekick.

We've planning to diagnose the root cause of these faults and would like to test with different version of alpine.

Thanks.

### PR DESCRIPTION
**Pull request by ashleyhull-versent**
Closes #233

### CODE REVIEW

**Comment by tianon** [comment]
I'm not sure how I feel about adding a new variant based on Alpine 3.6 (especially as we're trying to move forward into Alpine 3.8 to replace 3.7 by default) -- I think the release last week (for the `apk` security fix) was more the exception than the norm, and that Alpine 3.6's ship has really sailed generally except for severe security vulnerabilities.

**Comment by ashleyhull-versent** [comment]
using ruby 2.5.1 for example.. 
* alpine 3.6 doesn't exist (seems to work fine)
* alpine 3.7 crashes
* alpine 3.8 doesn't exist (pending next release)

There isn't really much of an option for me.. Just don't use 2.5?

**Comment by tianon** [comment]
Do you know why it crashes on 3.7?  I don't recall seeing any other reports
of issues like that with that combination, so it seems like an isolated
case and it would be useful if we could determine why it's happening and
whether there's anything we can do.

**Comment by ashleyhull-versent** [comment]
I'm happy to assist to put the pieces together but 

https://github.com/tootsuite/mastodon/pull/8712 is my revert due to the crash and includes my logs.

it's easily replicated by multiple people in the Mastodon community - I'm uncertain if they've lodged any ticket with sidekick.

**Pull request closed without merging**
