### PR TITLE
Drop support for 1.9

### PR DESCRIPTION
**Pull request by Moghedrin**
Drop support for 1.9 to match [upstream](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/).

### CODE REVIEW

**Comment by tianon** [comment]
:+1: LGTM (thanks for also pre-providing the link to upstream :heart:)

**Comment by yosifkit** [comment]
:imp: can you drop this line too? https://github.com/docker-library/ruby/blob/master/generate-stackbrew-library.sh#L7

**Comment by Moghedrin** [comment]
Oooh. Good catch.

**Comment by yosifkit** [comment]
Thanks!

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
