### PR TITLE
Bump ruby minor versions

### PR DESCRIPTION
**Pull request by cpuguy83**
2.2.2
2.1.6
2.0.0-p645

Signed-off-by: Brian Goff <cpuguy83@gmail.com>

### CODE REVIEW

**Comment by yosifkit** [comment]
Green travis, :heart:!  LGTM

**Comment by wfarr** [comment]
:ship:

**Comment by yosifkit** [comment]
Ping @tianon

**Comment by tianon** [comment]
LGTM

**Pull request merged**
