### PR TITLE
Add stretch variants of 2.3

### PR DESCRIPTION
**Pull request by fsateler**
I have built and the images appear to work OK

### CODE REVIEW

**Comment by tianon** [comment]
Can you explain the justification for the explicit `libssl1.0`? (c96c23d5aad649883350ed8468d495d5ba2ea2ab)

**Comment by fsateler** [comment]
@tianon because openssl 1.1 support came with ruby 2.4 :(

https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/

**Comment by yosifkit** [comment]
Sorry for the slow reply. :bowing_man:

These Dockerfiles seem fine, but there needs to be changes to `update.sh` and maybe the `Dockerfile-{debian,slim}.template` files so that the `libssl1.0-dev` change won't cause the auto update job to fail as it attempts to revert it.

https://github.com/docker-library/ruby/blob/ca5366d8e8afa5f6cf810a07740a50e1f4eeab36/update.sh#L82-L95

Probably just need to add something similar to the special case for `alpine3.4` to replace the `libssl-dev` in slim and add the line for non-slim.

**Comment by fsateler** [comment]
Hi, I updated update.sh. After I run it now, the only diff I get is due to the different tarball version, url and hash. The ssl1.0 changes are not lost. Is there anything else needed?

**Comment by fsateler** [comment]
Hi, friendly ping. Anything else missing I can help with so this can be merged?

**Comment by yosifkit** [comment]
Did a rebase on master to get #185. Swapped `update.sh` changes to simplify.

LGTM

**Pull request merged**
