### PR TITLE
Remove rc label from 2.5.0

### PR DESCRIPTION
**Pull request by ykzts**
- [Ruby 2.5.0 Released](https://www.ruby-lang.org/en/news/2017/12/25/ruby-2-5-0-released/)

### CODE REVIEW

**Comment by tianon** [comment]
This is technically a duplicate of https://github.com/docker-library/ruby/pull/177, but it needed only a single line change, where that one needed a bit more than that, so I'm merging this one.  Thanks! :+1:

**Comment by ethagnawl** [comment]
Does anyone know if there's an `onbuild` variant in the works for 2.5.0? If not, I'd be happy to submit a PR.

**Comment by tianon** [comment]
Nope, it was deprecated and intentionally removed -- see https://github.com/docker-library/docs/pull/911 and https://github.com/docker-library/official-images/issues/2076.

**Comment by ethagnawl** [comment]
@tianon Oh, that's a bummer - I was hoping the upgrade to 2.5.0 would be a one-line change. Anyways, thanks for the info and the quick response.

**Pull request merged**
